server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 111111
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  #  config:
  #    import: optional:file:.env[.properties]  # .env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
    username: smuser
    password: ENC(wcpLb3m0/NbJ2urXvQXQiQ==)
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info

# Application Config

app:
  key:
    skey: ${MY_KEY}
